export const actions = {
    LOADING_FOODS: 'LOADING_FOODS',
    SET_FOODS: 'SET_FOODS',

    LOADING_FOOD_STATUS_CHOICES: 'LOADING_FOOD_STATUS_CHOICES',
    SET_FOOD_STATUS_CHOICES: 'SET_FOOD_STATUS_CHOICES'
}