export const actions = {
    LOADING_THEATERS: 'LOADING_THEATERS',
    SET_THEATERS: 'SET_THEATERS',

    LOADING_THEATER_STATUS_CHOICES: 'LOADING_THEATER_STATUS_CHOICES',
    SET_THEATER_STATUS_CHOICES: 'SET_THEATER_STATUS_CHOICES'
}